default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 256
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 7500000
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 10000
    use_recurrent: false
    vis_encode_type: simple
    behavioral_cloning:
        demo_path: C:/Users/Seppi/AppData/Local/gitkraken/app-7.0.0/ML-Agents-Example-DemonstrationLearning/Assets/PushBlockDemonst_0.demo
        strength: 0.5
        steps: 100000
    reward_signals:
        gail:
            strength: 0.2
            gamma: 0.99
            encoding_size: 128
            demo_path: C:/Users/Seppi/AppData/Local/gitkraken/app-7.0.0/ML-Agents-Example-DemonstrationLearning/Assets/PushBlockDemonst_0.demo
        extrinsic:
            strength: 0.8
            gamma: 0.99

